sudo: true
language: generic
services:
  - mysql
before_script:
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - echo "[mysqld]\n\rsecure_file_priv=~/owl_data" > ~travis/.my.cnf
  - sudo systemctl restart mysql 
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mkdir ~/out
  - chmod +x scripts/*.sh
  - chmod +x statistics/*.sh
  - ./scripts/travis.sh
script:
  - ./scripts/init_mysql.sh
  - ./statistics/stats.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: out
  target_branch: gh-pages
  on:
    branch: main
