sudo: true
language: ruby
rvm: 
  - 2.5
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
services:
  - mysql
before_script:
  - sudo apt-get install chromium-driver
  - sudo apt-get --only-upgrade install google-chrome-stable
  - mkdir /home/travis/build/louismeunier/owl-stats/out
  - chmod +x scripts/*.sh
  - chmod -R +x statistics/*.sh
  - ./scripts/upgrade_mysql.sh
  - ./scripts/travis.sh
script:
  - ./scripts/init_mysql.sh
  - ./statistics/stats.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: out
  target_branch: gh-pages
  on:
    branch: main
