sudo: true
language: generic
services:
  - mysql
before_script:
  - mkdir /home/travis/build/louismeunier/owl-stats/out
  - chmod +x scripts/*.sh
  - chmod +x statistics/*.sh
  - ./scripts/upgrade_mysql.sh
  - ./scripts/travis.sh
script:
  - ./scripts/init_mysql.sh
  - ./statistics/stats.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: out
  target_branch: gh-pages
  on:
    branch: main
